In [1]:
list1=[1,2,3]

In [2]:
for i in range(0,len(list1)):
    list1[i]=list1[i]+1

In [3]:
list1

[2, 3, 4]

In [5]:
import numpy as np

In [6]:
np_arr = np.array([1,2,3,4])

In [7]:
type(np_arr)

numpy.ndarray

In [8]:
np_arr+1

array([2, 3, 4, 5])

In [9]:
np_aar1=np.array([1,2,3,4])

In [11]:
# To check the numpy dimension
np_aar1.ndim

1

In [13]:
#Number of elements in the numpy array
np_aar1.size

4

In [14]:
np.mean(np_aar1)

2.5

In [15]:
np.median(np_aar1)

2.5

In [16]:
np.std(np_aar1)

1.118033988749895

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
a=np.arange(30)

In [21]:
type(a)

numpy.ndarray

In [23]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np_aar1

array([1, 2, 3, 4])

In [27]:
twodim=np.array([[1,2,3,4],[2,3,4,5]])

In [28]:
twodim

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [29]:
twodim.size

8

In [30]:
twodim.shape

(2, 4)

In [31]:
np.mean(twodim)

3.0

In [33]:
np.mean(twodim,axis=0)

array([1.5, 2.5, 3.5, 4.5])

In [35]:
np_a=np.arange(35)

In [36]:
np_a.ndim

1

In [37]:
np_a.dtype

dtype('int32')

In [43]:
np_a.shape=(5,7)

In [41]:
np_a.ndim

2

In [46]:
np_a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [47]:
np_a_2=np_a.reshape(7,5)

In [48]:
np_a_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [54]:
np.random.random(10)

array([0.13053293, 0.18682856, 0.03549536, 0.41090743, 0.61717152,
       0.43326535, 0.69342436, 0.62533623, 0.54859957, 0.13869276])

In [55]:
np.random.randint(10,size=20)

array([9, 0, 2, 0, 8, 9, 7, 3, 6, 1, 6, 6, 3, 8, 0, 1, 8, 4, 2, 2])

In [57]:
np.random.rand(3,2)

array([[0.37509543, 0.84449433],
       [0.52493867, 0.43200617],
       [0.11486616, 0.83818156]])

In [58]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

In [59]:
np.ones(35)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [60]:
np.zeros(35)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])